version: "3"

services:
  cliente:
    build: ./cliente
    ports:
      - "8080:8080"
    depends_on:
      - servidor
    networks:
      - imagen-net

  servidor:
    build: ./servidor
    ports:
      - "50051:50051"
    networks:
      - imagen-net
    environment:
      - NODOS_DISPONIBLES=nodo1:50052,nodo2:50052,nodo3:50052,nodo4:50052

  nodo1:
    build: ./nodos
    ports:
      - "50052:50052"
    networks:
      - imagen-net
    

  nodo2:
    build: ./nodos
    ports:
      - "50052:50052"
    networks:
      - imagen-net
    

  nodo3:
    build: ./nodos
    ports:
      - "50052:50052"
    networks:
      - imagen-net
    

  nodo4:
    build: ./nodos
    ports:
      - "50052:50052"
    networks:
      - imagen-net

networks:
  imagen-net:
    driver: bridge
