services:
  gluster1:
    image: gluster/gluster-centos:latest
    hostname: gluster1
    privileged: true
    volumes:
      - gluster1-brick:/data/brick1
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - imagen-net
    command: >
      bash -c "
        glusterd &&
        sleep 10 &&
        gluster peer probe gluster2 &&

        gluster volume create gvol replica 2 gluster1:/data/brick1 gluster2:/data/brick1 force &&

        gluster volume start gvol &&
        gluster volume set gvol auth.allow '*' &&

        #gluster volume info gvol &&
        #gluster volume status gvol &&
        tail -f /var/log/glusterfs/glusterd.log
      "
  gluster2:
    image: gluster/gluster-centos:latest
    hostname: gluster2
    privileged: true
    volumes:
      - gluster2-brick:/data/brick1
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - imagen-net
    command: >
      bash -c "
        glusterd -N
      "
  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    ports:
      - "8080:8080"
    privileged: true
    environment:
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    depends_on:
      - gluster1
      - gluster2
      - nodo1
      - nodo2
      - nodo3
      - nodo4
    networks:
      - imagen-net

  nodo1:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50052:50052"  # procesamiento
      - "50053:50053"  # bully
    environment:
      - NODO_ID=1
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo2:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50054:50052"  # procesamiento
      - "50055:50053"  # bully
    environment:
      - NODO_ID=2
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo3:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50056:50052"  # procesamiento
      - "50057:50053"  # bully
    environment:
      - NODO_ID=3
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo4:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50058:50052"  # procesamiento
      - "50059:50053"  # bully
    environment:
      - NODO_ID=4
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

volumes:
  gluster1-brick:
    driver: local
  gluster2-brick:
    driver: local

networks:
  imagen-net:
    driver: bridge