services:
  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nodo1
      - nodo2
      - nodo3
      - nodo4
    networks:
      - imagen-net

  nodo1:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50052:50052"  # procesamiento
      - "50053:50053"  # bully
    environment:
      - NODO_ID=1
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo2:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50052:50052"  # procesamiento
      - "50053:50053"  # bully
    environment:
      - NODO_ID=2
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo3:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50052:50052"  # procesamiento
      - "50053:50053"  # bully
    environment:
      - NODO_ID=3
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

  nodo4:
    build:
      context: .
      dockerfile: nodos/Dockerfile
    ports:
      - "50052:50052"  # procesamiento
      - "50053:50053"  # bully
    environment:
      - NODO_ID=4
      - NODOS_CONOCIDOS=nodo1:50053,nodo2:50053,nodo3:50053,nodo4:50053
    networks:
      - imagen-net

networks:
  imagen-net:
    driver: bridge
