apiVersion: v1
kind: Service
metadata:
  name: cliente-service
  namespace: imagen-processing
  labels:
    app: cliente-flask
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
  selector:
    app: cliente-flask
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-flask
  namespace: imagen-processing
spec:
  replicas: 2  # Alta disponibilidad
  selector:
    matchLabels:
      app: cliente-flask
  template:
    metadata:
      labels:
        app: cliente-flask
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: cliente
        image: cliente-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODOS_CONOCIDOS
          value: "nodos-service.imagen-processing.svc.cluster.local:50053"
        - name: GLUSTER_ENABLED
          value: "true"
        - name: GLUSTER_MOUNT_POINT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GLUSTER_MOUNT_POINT
        volumeMounts:
        - name: gluster-volume
          mountPath: /mnt/almacenamiento_dist
        - name: local-storage
          mountPath: /usr/src/app/subidos
        - name: local-storage
          mountPath: /usr/src/app/procesados
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /cluster/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      # montar glusterFS
      initContainers:
      - name: gluster-mount
        image: gluster/gluster-centos:latest
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y glusterfs-client
          mkdir -p /mnt/almacenamiento_dist
          
          until gluster --remote-host=glusterfs-cluster.imagen-processing.svc.cluster.local volume info gvol; do
            sleep 10
          done
          
          mount -t glusterfs glusterfs-cluster.imagen-processing.svc.cluster.local:gvol /mnt/almacenamiento_dist
        volumeMounts:
        - name: gluster-volume
          mountPath: /mnt/almacenamiento_dist
          mountPropagation: Bidirectional
      volumes:
      - name: gluster-volume
        emptyDir: {}
      - name: local-storage
        emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cliente-ingress
  namespace: imagen-processing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/client-max-body-size: "20m"
spec:
  rules:
  - host: imagen-processing.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cliente-service
            port:
              number: 8080