# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/bully.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/bully.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/bully.proto\"\"\n\x0f\x45leccionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"\x1f\n\rEleccionReply\x12\x0e\n\x06status\x18\x01 \x01(\t\",\n\x12\x43oordinadorRequest\x12\x16\n\x0e\x63oordinador_id\x18\x01 \x01(\x05\"\"\n\x10\x43oordinadorReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"2\n\x0eHeartbeatReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08is_alive\x18\x02 \x01(\x08\"#\n\x10RespuestaRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\" \n\x0eRespuestaReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd5\x01\n\x0c\x42ullyService\x12,\n\x08\x45leccion\x12\x10.EleccionRequest\x1a\x0e.EleccionReply\x12\x35\n\x0b\x43oordinador\x12\x13.CoordinadorRequest\x1a\x11.CoordinadorReply\x12/\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x0f.HeartbeatReply\x12/\n\tRespuesta\x12\x11.RespuestaRequest\x1a\x0f.RespuestaReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bully_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECCIONREQUEST']._serialized_start=21
  _globals['_ELECCIONREQUEST']._serialized_end=55
  _globals['_ELECCIONREPLY']._serialized_start=57
  _globals['_ELECCIONREPLY']._serialized_end=88
  _globals['_COORDINADORREQUEST']._serialized_start=90
  _globals['_COORDINADORREQUEST']._serialized_end=134
  _globals['_COORDINADORREPLY']._serialized_start=136
  _globals['_COORDINADORREPLY']._serialized_end=170
  _globals['_HEARTBEATREQUEST']._serialized_start=172
  _globals['_HEARTBEATREQUEST']._serialized_end=207
  _globals['_HEARTBEATREPLY']._serialized_start=209
  _globals['_HEARTBEATREPLY']._serialized_end=259
  _globals['_RESPUESTAREQUEST']._serialized_start=261
  _globals['_RESPUESTAREQUEST']._serialized_end=296
  _globals['_RESPUESTAREPLY']._serialized_start=298
  _globals['_RESPUESTAREPLY']._serialized_end=330
  _globals['_BULLYSERVICE']._serialized_start=333
  _globals['_BULLYSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
