# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/procesador.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/procesador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/procesador.proto\"\x1d\n\rImagenRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"1\n\x0bImagenReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x32\x42\n\x10ProcesadorImagen\x12.\n\x0eProcesarImagen\x12\x0e.ImagenRequest\x1a\x0c.ImagenReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.procesador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGENREQUEST']._serialized_start=26
  _globals['_IMAGENREQUEST']._serialized_end=55
  _globals['_IMAGENREPLY']._serialized_start=57
  _globals['_IMAGENREPLY']._serialized_end=106
  _globals['_PROCESADORIMAGEN']._serialized_start=108
  _globals['_PROCESADORIMAGEN']._serialized_end=174
# @@protoc_insertion_point(module_scope)
